### ISSUE TITLE
Add data to transferred effects from the item that created it

### ISSUE THREAD

**Issue by krbz999** [GamerFlix/effective-transferral#34]
> and then mention that clean_up should probably make use of it too

**Comment by GamerFlix** [comment]
Since the origin is a system populated field the planned solution for this would be to apply a custom flag to the effect instead with the expected uuid.
Since this way effects that have been transferred can also be identified by Effective Transferral the label editing and clean up method can be simplified.

**Comment by krbz999** [comment]
Current ideas to add to effects' flags:
- `origin` (a string, the uuid of the item that created the effects).
- `level` (an integer, the level of the item if it was a spell).
